spring:
  application:
    name: stock-sender
  activemq:
    user: admin
    password: admin
    broker-url: tcp://localhost:61616
  kafka:
    bootstrap-servers: localhost:9092  
server:
  port: 9090