spring:
  application:
    name: stock-receiver
  activemq:
    user: admin
    password: admin
    broker-url: tcp://localhost:61616
  kafka:
   consumer:
     group-id: consumer-group-dashboard
     auto-offset-reset: earliest
   bootstrap-servers: localhost:9092  
